all:
  children:
    control:
      hosts:
        control:
          ansible_host: 65.108.54.239
    workspace:
      hosts:
        workspace:
          ansible_host: 135.181.82.35
    desktop_pool:
      hosts:
        desktop_pool:
          ansible_host: 46.62.135.73
    guac_lb:
      hosts:
        guac_lb:
          ansible_host: 203.0.113.10
          guac_domain: guac.example.com
          letsencrypt_email: admin@example.com
