all:
  children:
    control:
      hosts:
        control:
          ansible_connection: ssh
    workspace:
      hosts:
        workspace:
          ansible_connection: ssh
    desktop_pool:
      hosts:
        desktop_pool:
          ansible_connection: ssh
