all:
  children:
    control:
      hosts:
        control:
          ansible_host: ${module.control_node.server_ip}
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_connection: ssh
          guac_rdp_password: ${module.control_node.root_password}
    workspace:
      hosts:
        workspace:
          ansible_connection: ssh
    desktop_pool:
      hosts:
        desktop_pool:
          ansible_connection: ssh
